name: "RDP via Tailscale + RustDesk (Workflow A)"

on:
  workflow_dispatch:
    inputs:
      ts_tailnet:        { description: "Tailscale tailnet (e.g. you@gmail.com)", required: true }
      ts_api_key:        { description: "Tailscale API key (device admin, no 'Bearer')", required: true }
      ts_authkey:        { description: "Tailscale Auth key (reusable or ephemeral)", required: true }
      quick_test:
        description: "Run 5-minute quick test"
        type: boolean
        default: false
      runtime_minutes:   { description: "Runtime (max 360; default 355; ignored if quick_test=true)", required: false, default: "355" }
      do_purge:          { description: "Purge bullet* at start", required: false, default: "true" }

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: pwsh

jobs:
  rdp:
    runs-on: windows-2025
    timeout-minutes: 370

    steps:
      - name: Setup Tailscale + RDP
        run: |
          $ErrorActionPreference = "Stop"
          function Yes($v){ "$v" -match '^(?i:true|1|yes|on)$' }

          $runtime = [int]"${{ inputs.runtime_minutes }}"
          if (Yes("${{ inputs.quick_test }}")) { $runtime = 5 }
          if ($runtime -gt 360) { $runtime = 355 }
          "RUNTIME_MINUTES=$runtime" | Out-File -FilePath $env:GITHUB_ENV -Append

          # Purge old bullet devices
          if (Yes("${{ inputs.do_purge }}")) {
            try {
              $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${{ inputs.ts_api_key }}:"))
              $tn   = [System.Uri]::EscapeDataString("${{ inputs.ts_tailnet }}")
              $resp = Invoke-RestMethod -Uri "https://api.tailscale.com/api/v2/tailnet/$tn/devices" -Headers @{ Authorization = "Basic $auth" }
              foreach ($d in $resp.devices) {
                if ($d.hostname -like "bullet*") {
                  Invoke-RestMethod -Method Delete -Uri "https://api.tailscale.com/api/v2/device/$($d.id)" -Headers @{ Authorization = "Basic $auth" } -ErrorAction SilentlyContinue
                }
              }
              Write-Host "Purged existing bullet* devices"
            } catch { Write-Host "Purge warning: $($_.Exception.Message)" }
          }

          # Install Tailscale
          $tsExe = "C:\Program Files\Tailscale\tailscale.exe"
          if (-not (Test-Path $tsExe)) {
            $url = "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe"
            $dst = "$env:TEMP\ts.exe"
            Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
            Start-Process -FilePath $dst -ArgumentList "/quiet" -Wait
          }
          Start-Service Tailscale -ErrorAction SilentlyContinue
          & $tsExe logout | Out-Null
          & $tsExe up --authkey "${{ inputs.ts_authkey }}" --hostname "bullet" --accept-routes --accept-dns=false

          # RDP account
          $user="Bullettemporary"; $pass="Bullet@12345"
          $sec = ConvertTo-SecureString $pass -AsPlainText -Force
          if (-not (Get-LocalUser -Name $user -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $user -Password $sec -AccountNeverExpires
            Add-LocalGroupMember -Group Administrators -Member $user
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $user
          }
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          $ip4 = (& $tsExe ip -4 | Select-Object -First 1)
          Write-Host "RDP login → user=$user pass=$pass ip=$ip4"

      - name: Install RustDesk (EXE, no MSI) + Get ID
        run: |
          $ErrorActionPreference = "Stop"
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

          $exe = "$env:TEMP\rustdesk.exe"
          $url = "https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-x86_64.exe"
          Invoke-WebRequest -Uri $url -OutFile $exe -UseBasicParsing

          if (-not (Test-Path $exe)) { throw "RustDesk EXE not downloaded" }

          Start-Process $exe -ArgumentList "/verysilent /norestart" -Wait

          $rustExe = "C:\Program Files\RustDesk\rustdesk.exe"
          if (-not (Test-Path $rustExe)) { $rustExe = "C:\Program Files (x86)\RustDesk\rustdesk.exe" }
          if (-not (Test-Path $rustExe)) { throw "RustDesk not found after EXE install" }

          $pwd = (New-Guid).Guid.Substring(0,8)
          Start-Process -FilePath $rustExe
          Start-Sleep -Seconds 12
          try { & $rustExe --password $pwd } catch {}

          $id = ""
          for ($i=0; $i -lt 20 -and -not $id; $i++) {
            try { $out = & $rustExe --get-id 2>$null; if ($out) { $id = $out.Trim() } } catch {}
            if (-not $id -and (Test-Path "C:\ProgramData\RustDesk\id")) {
              $maybe = Get-Content "C:\ProgramData\RustDesk\id" -ErrorAction SilentlyContinue | Select-Object -First 1
              if ($maybe) { $id = $maybe.Trim() }
            }
            if (-not $id) { Start-Sleep -Seconds 3 }
          }
          if (-not $id) { $id = "unknown" }

          "RUSTDESK_ID=$id"   | Out-File -FilePath $env:GITHUB_ENV -Append
          "RUSTDESK_PWD=$pwd" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Show RustDesk ID + Password in logs
        run: |
          Write-Host "RustDesk ID = $env:RUSTDESK_ID"
          Write-Host "RustDesk PASSWORD = $env:RUSTDESK_PWD"

      - name: Screenshot & Upload to GoFile
        run: |
          Add-Type -AssemblyName System.Windows.Forms
          Add-Type -AssemblyName System.Drawing
          $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
          $bmp = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
          $gfx = [System.Drawing.Graphics]::FromImage($bmp)
          $gfx.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
          $file = "$env:GITHUB_WORKSPACE\rustdesk-login.png"
          $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)

          $server = (Invoke-RestMethod https://api.gofile.io/getServer).data.server
          $resp = Invoke-RestMethod -Uri "https://$server.gofile.io/contents/uploadfile" -Method Post -Form @{ "file" = Get-Item $file }
          $link = $resp.data.directLink
          if (-not $link) { $link = $resp.data.downloadPage }
          Write-Host "RustDesk Screenshot GoFile Link: $link"

      - name: Keep alive
        run: |
          $end=(Get-Date).AddMinutes([int]$env:RUNTIME_MINUTES)
          while((Get-Date) -lt $end){ Start-Sleep -Seconds 60 }
